name = "splitr-landing"
compatibility_date = "2025-03-22"
pages_build_output_dir = "dist"

# KV namespace for waitlist emails
[[kv_namespaces]]
binding = "WAITLIST"
id = "a6da644ec77a4b71a1bc70b259393cbc"
preview_id = "0c508da423d340438e396fea62feacb3"
